### ISSUE TITLE
Interestingness score

### ISSUE THREAD

**Issue by odunkel** [argoverse/av2-api#103]
Hey,

you were roughly explaining the interestingness score in your paper and in the supplementaries. Are you planning to share more details about the process of selecting interesting scenarios or is this confidential functionality?

I am looking forward to your answer.

Best regards

**Comment by wqi** [comment]
Hi @odunkel, thanks for your interest in the motion forecasting dataset!

At a high level, the interestingness score is a sum of four different types of score types, which are intended to encourage the selection of scenarios which exhibit:

- Kinematic complexity
- Map complexity
- Social complexity
- AV relevance

The kinematic score associated with each scenario is made up of the following components:

- Non-straight score (promotes scenarios with focal tracks that exhibit curvature)
- Blind turn score (promotes scenarios with straight line trajectories in the observed segment, but contain turns in the prediction horizon)
- Velocity change score (promotes scenarios with significant changes in speed)
- Includes stop score (promotes scenarios which start or end at a stop)

Social score components include:

- Agent type score (encourages a diverse distribution of focal agent types)
- Actor density score (promotes interaction density within scenarios)

Please let me know if this helps! Happy to discuss any of the scoring components in additional detail if it's useful for the community.
