### ISSUE TITLE
how get agent size in motion forecasting dataset?

### ISSUE THREAD

**Issue by betterqiang** [argoverse/av2-api#136]
I can get agent P V ID in .parquet
but how to get it size?
Thanks

**Comment by wqi** [comment]
Hi @betterqiang, ground truth information about actor dimensions (as inferred by tracking) is unfortunately not available in the current version of the AV2 MF dataset.

**Comment by James-Hays** [comment]
@betterqiang To add to what William said, even though the dataset doesn't have geometric dimensions for each actor, it does have the category of each actor, and there's not that much variance in size within each category. E.g. if you use the average dimensions of a pedestrian, a car, a cyclist, etc I think it will be a pretty good approximation.

**Comment by betterqiang** [comment]
Thank you for the answer.
 I obtained the  size of the agent from the Sensor dataset and provided an approximate size.
