### ISSUE TITLE
Fail to evaluation in av2 motion forecasting

### ISSUE THREAD

**Issue by JieMaMagic** [argoverse/av2-api#149]
Hi,

What does the definition of 'all scored actors' mean specifically?  focal_track_id  or  track_id in scenario_serialization?

I am looking forward to your answer.

Best regards

**Comment by wqi** [comment]
Hi @JieMaMagic, apologies for the delayed response.

#154 covers some similar questions and should be helpful here.

Closing out this issue for now, but please feel free to re-open if you have any more questions! :-)

**Comment by JieMaMagic** [comment]
Thank you. Your email is received and will be handled  as soon as possible

您的邮件已收到，我会尽快处理
