### ISSUE TITLE
Missing of Argoverse 2 Lidar Dataset dowanload link

### ISSUE THREAD

**Issue by VictorLlu** [argoverse/av2-api#161]
The download insturction link of Argoverse 2 Lidar Dataset:
https://github.com/argoai/argoverse2-api/blob/main/DOWNLOAD.md
shows 404 error. 
Would you please help me accessing a feasible instruction?

**Comment by Kin-Zhang** [comment]
I also found that!

Here is the random commit I found the file: https://github.com/argoverse/av2-api/blob/b8f362f115f223f9cb89f3ae1fbcd091469b2df7/DOWNLOAD.md

But the README has some problem... The download should be
```bash
s5cmd --no-sign-request cp 's3://argoai-argoverse/av2/lidar/*' /home/kin/bags/av2
```

**Comment by Kin-Zhang** [comment]
By the way, no annotation in lidar dataset... mentioned here: https://www.argoverse.org/av2.html#lidar-link

> The Argoverse 2 Lidar Dataset is a collection of 20,000 scenarios with lidar sensor data, HD maps, and ego-vehicle pose. It does not include imagery or 3D annotations. The dataset is designed to support research into self-supervised learning in the lidar domain, as well as point cloud forecasting.
