### ISSUE TITLE
Cover image [Point Cloud/LiDAR Color] in av2

### ISSUE THREAD

**Issue by Kin-Zhang** [argoverse/av2-api#166]
I want to know if there is any code snippet to show the cover image [or color the lidar point cloud quickly]:
![image](https://user-images.githubusercontent.com/35365764/233859539-957aa903-c6c4-45bb-9a04-c395b231f6c3.png)

Since the lidar is combined by upper and down together, when I want to color the point cloud is hard to decide which one should I go for? 

Thanks!

**Comment by argoverse-admin** [comment]
Hi @Kin-Zhang, thanks for your interest in Argoverse 2. Please refer to the code found here: https://github.com/argoverse/av2-api/pull/20/files

**Comment by Kin-Zhang** [comment]
Thanks!
