### ISSUE TITLE
(Motion Forecasting) How to select 5 timesteps as input from 50 past samples?

### ISSUE THREAD

**Issue by xzag008** [argoverse/av2-api#190]
Hi,

I want to submit my prediction results to EvalAI but I don't know how to select the first timestep from 50 past samples:
According to 10Hz sampling frequency and 5 past timesteps, the selected indexes from 50 past samples can be set to [0, 10, 20, 30, 40], [1, 11..., 41],..., or [9, 19, 29, 39, 49].
Which one should I choose to match the challenge in EvalAI?

**Comment by wqi** [comment]
Hi @xzag008, apologies for the delayed response. 

For AV2 MF submissions, we do not prescribe any particular methodology for how inputs should be consumed. You're free to consume as many or as few of the historical object states as you would like.
