### ISSUE TITLE
pointcloud motion compensation 

### ISSUE THREAD

**Issue by Kailthen** [argoverse/av2-api#204]
1 is the [x,y,z] fields in pointcloud undistorted ?
2 if not, how can i do this myself ?

thanks

**Comment by Kailthen** [comment]
From https://argoverse.github.io/user-guide/datasets/sensor.html,
Both lidars have their own reference frame, and we refer to them as up_lidar and down_lidar, respectively. We have **egomotion-compensated** the LiDAR sensor data to the egovehicle reference nanosecond timestamp

**Comment by Wolfybox** [comment]
> From https://argoverse.github.io/user-guide/datasets/sensor.html, Both lidars have their own reference frame, and we refer to them as up_lidar and down_lidar, respectively. We have **egomotion-compensated** the LiDAR sensor data to the egovehicle reference nanosecond timestamp

I notice that if the timestamp is larger, mere egomotion-compensated is not enough to align the bbox. Maybe taking the obj motion into consideration as well would solve this?
