### ISSUE TITLE
ERROR: Failed building wheel for av2

### ISSUE THREAD

**Issue by Qingfeng800** [argoverse/av2-api#213]
@kylevedder Hi, when I run "pip install git+https://github.com/argoverse/av2-api#egg=av2" ,I met a problem as below, do you know what's the problem?
`Building wheels for collected packages: av2
  Building wheel for av2 (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for av2 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [144 lines of output]
      Running `maturin pep517 build-wheel -i /home/qf/anaconda3/envs/QCNet/bin/python --compatibility off`
      📦 Including license file "/tmp/pip-install-v6_i79xk/av2_eca7bad977324933b5d12e91450b043e/NOTICE"
      🍹 Building a mixed python/rust project
      🔗 Found pyo3 bindings
      🐍 Found CPython 3.8 at /home/qf/anaconda3/envs/QCNet/bin/python
      📡 Using build options features from pyproject.toml
         Compiling autocfg v1.1.0
         Compiling libc v0.2.141
         Compiling proc-macro2 v1.0.56
         Compiling unicode-ident v1.0.8
         Compiling quote v1.0.26
         Compiling cfg-if v1.0.0
         Compiling libm v0.2.6
         Compiling scopeguard v1.1.0
         Compiling syn v1.0.109
         Compiling crossbeam-utils v0.8.15
         Compiling memchr v2.5.0
         Compiling futures-core v0.3.28
         Compiling once_cell v1.17.1
         Compiling serde_derive v1.0.160
         Compiling futures-sink v0.3.28
         Compiling version_check v0.9.4
         Compiling adler v1.0.2
         Compiling static_assertions v1.1.0
         Compiling serde v1.0.160
         Compiling log v0.4.17
         Compiling rayon-core v1.11.0
         Compiling crc32fast v1.3.2
         Compiling either v1.8.1
         Compiling pkg-config v0.3.26
         Compiling futures-task v0.3.28
         Compiling futures-channel v0.3.28
         Compiling pin-project-lite v0.2.9
         Compiling target-features v0.1.3
         Compiling futures-util v0.3.28
         Compiling pin-utils v0.1.0
         Compiling semver v1.0.17
         Compiling futures-io v0.3.28
         Compiling smallvec v1.10.0
         Compiling zstd-safe v6.0.5+zstd.1.5.4
         Compiling async-trait v0.1.68
         Compiling bitflags v1.3.2
         Compiling alloc-no-stdlib v2.0.4
         Compiling regex-syntax v0.6.29
         Compiling snap v1.1.0
         Compiling parking_lot_core v0.9.7
         Compiling iana-time-zone v0.1.56
         Compiling array-init-cursor v0.2.0
         Compiling rawpointer v0.2.1
         Compiling fallible-streaming-iterator v0.1.9
         Compiling seq-macro v0.3.3
         Compiling thiserror v1.0.40
         Compiling signal-hook v0.3.15
         Compiling base64 v0.21.0
         Compiling simdutf8 v0.1.4
         Compiling strength_reduce v0.2.4
         Compiling rustversion v1.0.12
         Compiling target-lexicon v0.12.6
         Compiling dyn-clone v1.0.11
         Compiling foreign_vec v0.1.0
         Compiling ethnum v1.3.2
         Compiling streaming-iterator v0.1.9
         Compiling hash_hasher v2.0.3
         Compiling unicode-width v0.1.10
         Compiling ppv-lite86 v0.2.17
         Compiling heck v0.4.1
         Compiling hashbrown v0.12.3
         Compiling strum v0.24.1
         Compiling xxhash-rust v0.8.6
         Compiling simd-adler32 v0.3.5
         Compiling fast-float v0.2.0
         Compiling bytes v1.4.0
         Compiling io-lifetimes v1.0.10
         Compiling paste v1.0.12
         Compiling typenum v1.16.0
         Compiling weezl v0.1.7
         Compiling bitflags v2.2.1
         Compiling rustix v0.37.13
         Compiling glob v0.3.1
         Compiling half v2.2.1
         Compiling bit_field v0.10.2
         Compiling portable-atomic v0.3.19
         Compiling indoc v1.0.9
         Compiling color_quant v1.1.0
         Compiling lexical-util v0.8.5
         Compiling unindent v0.1.11
         Compiling linux-raw-sys v0.3.7
         Compiling jpeg-decoder v0.3.0
         Compiling lebe v0.5.2
         Compiling miniz_oxide v0.6.2
         Compiling lazy_static v1.4.0
         Compiling alloc-stdlib v0.2.2
         Compiling zune-core v0.2.14
         Compiling fnv v1.0.7
         Compiling planus v0.3.1
         Compiling anyhow v1.0.70
         Compiling byteorder v1.4.3
         Compiling same-file v1.0.6
         Compiling termcolor v1.2.0
         Compiling number_prefix v0.4.0
         Compiling streaming-decompression v0.1.2
         Compiling rustc-hash v1.1.0
         Compiling humantime v2.1.0
         Compiling itertools v0.10.5
         Compiling brotli-decompressor v2.3.4
         Compiling ahash v0.8.3
         Compiling zune-inflate v0.2.53
         Compiling fdeflate v0.3.0
         Compiling miniz_oxide v0.7.1
         Compiling polars v0.28.0
         Compiling walkdir v2.3.3
         Compiling gif v0.12.0
         Compiling num-traits v0.2.15
         Compiling memoffset v0.8.0
         Compiling num-integer v0.1.45
         Compiling crossbeam-epoch v0.9.14
         Compiling lock_api v0.4.9
         Compiling slab v0.4.8
         Compiling smartstring v1.0.1
         Compiling indexmap v1.9.3
         Compiling tokio v1.27.0
         Compiling num-rational v0.4.1
         Compiling thread_local v1.1.7
         Compiling lexical-write-integer v0.8.5
         Compiling lexical-parse-integer v0.8.6
         Compiling rustc_version v0.4.0
      error: could not compile `proc-macro2` (lib) due to 2 previous errors
      warning: build failed, waiting for other jobs to finish...
      💥 maturin failed
        Caused by: Failed to build a native library through cargo
        Caused by: Cargo build finished with "exit status: 101": `PYO3_ENVIRONMENT_SIGNATURE="cpython-3.8-64bit" PYO3_PYTHON="/home/qf/anaconda3/envs/QCNet/bin/python" PYTHON_SYS_EXECUTABLE="/home/qf/anaconda3/envs/QCNet/bin/python" "cargo" "rustc" "--release" "--features" "pyo3/extension-module" "--manifest-path" "/tmp/pip-install-v6_i79xk/av2_eca7bad977324933b5d12e91450b043e/rust/Cargo.toml" "--message-format" "json" "--lib" "--crate-type" "cdylib"`
      error[E0635]: unknown feature `proc_macro_span_shrink`
        --> /home/qf/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.56/src/lib.rs:92:30
         |
      92 |     feature(proc_macro_span, proc_macro_span_shrink)
         |                              ^^^^^^^^^^^^^^^^^^^^^^
      
      
      error: aborting due to previous error
      
      
      For more information about this error, try `rustc --explain E0635`.
      
      Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/home/qf/anaconda3/envs/QCNet/bin/python', '--compatibility', 'off'] returned non-zero exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for av2
Failed to build av2
ERROR: Could not build wheels for av2, which is required to install pyproject.toml-based projects`

**Comment by kylevedder** [comment]
Why was I tagged in this?
