### ISSUE TITLE
Evaluations stuck for Argoverse2 test set 1719

### ISSUE THREAD

**Issue by kingwmk** [argoverse/av2-api#218]
Hello. 'Status is Submitted' when I submit my result file on evalai. But i can not get the returned evaluation results in the Single Agent Forecasting track. I also submit an issue [evalai](https://github.com/Cloud-CV/EvalAI/issues/4057).
Thank you!

**Comment by wqi** [comment]
Closing this issue out as evaluation servers appear to be healthy at this moment in time.
