### ISSUE TITLE
Enhancing Argoverse 2 Motion Forecasting Dataset: Adding Objects from Sensor Annotations

### ISSUE THREAD

**Issue by seokyeongbaek** [argoverse/av2-api#234]
Hello.
I am trying to make predictions using the Argoverse 2 Motion Forecasting Dataset.

I have confirmed that the ObjectType class in av2/datasets/motion_forecasting/data_schema.py consists of four Dynamic Movers.

Is it possible to add objects defined in av2/datasets/sensor/constants.py's annotationCategories class, such as 'WHEELED_DEVICE,' to the motion_forecasting ObjectType?

Does the data within the motion_forecasting dataset exclusively consist of objects defined in av2/datasets/motion_forecasting/data_schema.py?

Any feedback is appreciated.

**Comment by wqi** [comment]
Hi @seokyeongbaek, you are correct that the sensor dataset has a more detailed object ontology than the motion forecasting dataset.

Given that Argo has shut down and we no longer have access to raw data, we don't have any current plans to add additional object types to the MF dataset. However, given the large size of the MF dataset, the existing dataset almost certainly contains some instances of wheeled devices, likely under the pedestrian object type.
