### ISSUE TITLE
How is the heading in motion forecasting set defined?

### ISSUE THREAD

**Issue by aw0310** [argoverse/av2-api#241]
What is the centerline or base for the heading?
I found 'heading = 0' is in the direction of the positive y-axis (east).
Is this always the case?

**Comment by wqi** [comment]
Yes, headings in the AV2 MF dataset are consistent across scenarios and defined w.r.t a cartesian coordinate space aligned to cardinal directions.

In other words, a heading of 0 in different scenarios would always map to the same direction in the cartesian coordinate space.

**Comment by ZhanjunMei** [comment]
why positive y-axis is the east?

**Comment by wqi** [comment]
The positive Y-axis pointed east by convention in Argo maps, but it's an arbitrary convention that could be modified if necessary.
