### ISSUE TITLE
i have a question argoverse2  motion prediction leaderboard

### ISSUE THREAD

**Issue by jaeaehun** [argoverse/av2-api#248]
hello 
i am a student study time siries deep learning.
Are the input values the relative positions, heading angles, and speeds of agents with scored data from the perspective of the Autonomous Vehicle (AV)?
Is it mandatory to use map information?

thank you

**Comment by wqi** [comment]
Hi @jaeaehun, thanks for your interest in the motion prediction challenge!

The positions, heading angles, and kinematics are provided w.r.t. a cartesian coordinate space with fixed origin for each city (i.e. these values are not relative to the instantaneous position of the AV).

It is not mandatory to use map information in your model if your method does not require it. However, you may find it helpful to use map information to improve prediction performance.
