### ISSUE TITLE
Chance to get in competition rank list

### ISSUE THREAD

**Issue by DA21S321D** [argoverse/av2-api#251]
Hi, developers, sorry to bother you:
May i still have chance to get in the rank list in the ended competition "Argoverse 2 motion forcasting"(https://eval.ai/web/challenges/challenge-page/1719/overview), if i submit ? Will still my work be evaluated and scored and go on the rank list ? 
Thank for your great patience.

**Comment by James-Hays** [comment]
Hi!

The leaderboard should be up and operating, yes. While the 2023 competitions have ended, the 2024 competitions have started ( https://www.argoverse.org/tasks.html ). The top competitors will be highlighted at the CVPR 2024 Workshop on Autonomous Driving ( https://cvpr2024.wad.vision/ ).
