### ISSUE TITLE
Use of external data/model for the challenges

### ISSUE THREAD

**Issue by EloiZ** [argoverse/av2-api#256]
Hello,

Are the use of external public data or model weights allowed for the challenge participation (in particular the end-to-end forecasting challenge)?
For example,
- pretrained ImageNet feature extraction weights
- other public tracking dataset
- motion forecasting model pretrained on another public dataset

Thanks a lot,

**Comment by neeharperi** [comment]
Hi @EloiZ, 
You can absolutely use external public data or model weights for this challenge!

Thanks,
Neehar

**Comment by EloiZ** [comment]
Thanks a lot!
