### ISSUE TITLE
Submission blocked on Argoverse 2

### ISSUE THREAD

**Issue by kingwmk** [argoverse/av2-api#260]
Hello. I have a submission blocked problem on Argoverse 2: Motion Forecasting Competition's Multi-world prediction channel. 
The status always is 'submitted'.
Thank you for your help. https://eval.ai/web/challenges/challenge-page/1719/my-submission

**Comment by wqi** [comment]
Hi @kingwmk, thanks for reaching out!

The EvalAI has since been resolved - please feel free to re-open this issue if the problem persists.

**Comment by kingwmk** [comment]
Thank you so much for fixing this issue. However, I get a new problem that I can not upload the submission.parquet file. It blocked in the uploading process though I changed many networks.
![image](https://github.com/argoverse/av2-api/assets/19169383/d89303d2-f586-42dd-8f65-5b6b1c63f719)
