### ISSUE TITLE
Submission blocked on Argoverse 2 

### ISSUE THREAD

**Issue by kingwmk** [argoverse/av2-api#261]
Sorry, the problem comes out again.

**Comment by neeharperi** [comment]
Which challenge are you trying to submit to?

**Comment by kingwmk** [comment]
Argoverse 2 Multi-world prediction

**Comment by kingwmk** [comment]
> Which challenge are you trying to submit to?

Argoverse 2 Multi-World Forecasting (2024 Challenge)

**Comment by wqi** [comment]
Fixed, thanks for bringing this to our attention!

**Comment by kingwmk** [comment]
> Fixed, thanks for bringing this to our attention!

Thank you so much, doctor William Qi.
