### ISSUE TITLE
Question about heading

### ISSUE THREAD

**Issue by ChengkaiYang** [argoverse/av2-api#279]
Hi @wqi @neeharperi:
    I'd like to know what's the meaning of heading of focal object in motion forecating? In single agent prediction, some methods or models transform coordinate according to focal object's current location and heading. I think after transforming, we will change focal trajectory to be a trajectory which must satisfy:
  1) current location is [0.0, 0.0],
   2) current direction or velocity direction is **parallel to y axis**.
   Now 1) can be satisfied but 2) may not be satisfied. I would like to know where is the problem or we can not guarantee 2).
   Looking forward for your reply, thanks!

**Comment by wqi** [comment]
Hi @ChengkaiYang, apologies for the delayed response.

You're correct that methods which normalize trajectoreis for single-agent forecasting will often set the current position of the focal agent as the origin of the reference frame (0, 0).

Aligning the focal agent's heading wiht the positive X axis is a popular representation, but you could certainly choose to align with the Y axis instead. It's a design choice that shouldn't have too much of an impact on performance, as long as you're consistent with the transformation.
