### ISSUE TITLE
EvalAI Submission Blocked (status shows submited but can not run)

### ISSUE THREAD

**Issue by youngzhou1999** [argoverse/av2-api#281]
Hi @wqi @neeharperi 

I am trying to submit the single-world forecasting challenge before the deadline, but the submission is stuck at the status "Submitted". It seems like the server hasn't been running results for a long time (normally, this process takes less than 10 minutes). Could you please help me check if there is any issue?
I checked previous issues on GitHub and found that you guys have helped a lot of people address this problem. Thank you so much!

Best,
Yang

**Comment by wqi** [comment]
Hi Yang, thanks for the heads up and apologies for the delay -- we needed to apply a few updates to the evaluation server.

The system should be online and running smoothly again.
