### ISSUE TITLE
The Leaderboard submission for motion forecasting dataset.

### ISSUE THREAD

**Issue by bharilya** [argoverse/av2-api#283]
@benjaminrwilson , The leaderboard submission shows a status of "submitted," but the execution hasn't started, and no results are being generated. Could you please look into this issue?

**Comment by ZikangZhou** [comment]
I'm also facing the same issue. This may require some fixes. @wqi

**Comment by wqi** [comment]
Should be back up now, thanks for reporting the issue!

**Comment by bharilya** [comment]
The issue remains unchanged @wqi
