### ISSUE TITLE
Submission cannot run

### ISSUE THREAD

**Issue by Yurriki** [argoverse/av2-api#287]
@wqi Sorry for borthering you,however, my submission  on EvalAI cannot run and has been in a "submitted" state for a long time.  Is the server updating or is there any other issue?
Best wishes!

**Comment by wqi** [comment]
Should be back online now, thanks for your patience!

**Comment by XinGP** [comment]
@wqi Hello, I have also encountered a similar problem. When I was uploading the parcel file, the webpage got stuck and there was no response for a long time.

**Comment by XinGP** [comment]
Hello, I have also encountered a similar problem. When I was uploading the parquet file, the webpage got stuck and there was no response for a long time.

**Comment by wqi** [comment]
When were these submissions created? I checked the evaluation server and it doesn't seem like anything's currently stuck in queue.

**Comment by XinGP** [comment]
The submission was made just 10 minutes ago, and my ID is “whut-its
![屏幕截图 2024-12-13 155609](https://github.com/user-attachments/assets/ac1e1397-be05-4c17-9a14-627ca7dc0413)
”

**Comment by XinGP** [comment]
There are some issues with my description. I have been stuck here for almost an hour and decided to consult 10 minutes ago

**Comment by wqi** [comment]
This appears to be a problem with the EvalAI platform unfortunately. I checked the submission queue and it doesn't seem like an entry is being created for the evaluation server to run on.

I do recall a similar issue being raised about a year ago, which ended up being traced back to some kind of networking issue. Could you try 1) submitting using a different machine on a different network or 2) using the CLI?

**Comment by XinGP** [comment]
Sorry to bother you again, we found that uploading can be done normally on argoverse2 single, but Muti World has changed many machines and networks, including using CLI, and still cannot upload. Could you please check if your machine can upload normally?

**Comment by XinGP** [comment]
> @wqi Sorry to bother you again, we found that uploading can be done normally on argoverse2 single, but Muti World has changed many machines and networks, including using CLI, and still cannot upload. Could you please check if your machine can upload normally?

@wqi Thank you.

**Comment by wqi** [comment]
I was able to successfully upload and evaluate a parquet submission to the multi-world challenge, so it doesn't appear to be an issue with the evaluation server itself.

How large is your submission file? Anecdotally, it does seem like uploading large files to EvalAI can take a while.

**Comment by XinGP** [comment]
> I was able to successfully upload and evaluate a parquet submission to the multi-world challenge, so it doesn't appear to be an issue with the evaluation server itself.
> 
> How large is your submission file? Anecdotally, it does seem like uploading large files to EvalAI can take a while.

@wqi About 500mb, can you tell me if you uploaded it through web or CLI?

**Comment by XinGP** [comment]
> I was able to successfully upload and evaluate a parquet submission to the multi-world challenge, so it doesn't appear to be an issue with the evaluation server itself.
> 
> How large is your submission file? Anecdotally, it does seem like uploading large files to EvalAI can take a while.

![屏幕截图 2024-12-18 184512](https://github.com/user-attachments/assets/d06158ed-8703-4ff4-a645-ee745d9700c4)
It seems that the reason is that the file is too large

**Comment by XinGP** [comment]
@wqi Thank you for your multiple replies. This issue has been resolved. I can submit normally using CLI in Windows. CLI under Linux often reports errors and it is uncertain whether it is a bug.
