### ISSUE TITLE
Dose tracks include AV in Motion Forecasting dataset?

### ISSUE THREAD

**Issue by dongb5** [argoverse/av2-api#95]
Dose tracks include AV in Motion Forecasting dataset? The prediction of objects should consider the AV as well.

**Comment by ares89** [comment]
track.track_id == "AV"

**Comment by wqi** [comment]
Apologies for the late response, but @ares89 is correct. Each scenario also include's the AV's track history, which can be found by looking for the track with `track_id == "AV"`.
