### ISSUE TITLE
which from (x,y) corresponds to the longitudinal axis, Motion Forecasting Dataset? 

### ISSUE THREAD

**Issue by sop12** [argoverse/av2-api#96]
When reading the supplement material of Argoverse 2, it's there mentioned that the x axis corresponds to the driving direction, meaning by the way longitudinal axis. But the visualization of the speed for the tracked Actors (k=6) shows that the majority of x composante of the velocity is negative, something I find curious. So, which one from (x,y) corresponds to the longitudinal axis? Thanks for your upcoming response.

**Comment by wqi** [comment]
Hi @sop12, apologies for the delayed response.

Would you mind pointing me to the velocity visualization you're referring to?

Happy to look into this if you can point me to the specific figure.

Please feel free to re-open the issue when you get a chance to do so. :-)
